local api = require('spec.test_helper')
local json = require('dkjson')

describe('builders', function()
    describe('keyboard', function()
        it('creates a keyboard with defaults', function()
            local kb = api.keyboard()
            assert.is_table(kb)
            assert.is_table(kb.keyboard)
            assert.is_false(kb.resize_keyboard)
            assert.is_false(kb.one_time_keyboard)
            assert.is_false(kb.selective)
        end)

        it('creates a keyboard with options', function()
            local kb = api.keyboard(true, true, true)
            assert.is_true(kb.resize_keyboard)
            assert.is_true(kb.one_time_keyboard)
            assert.is_true(kb.selective)
        end)

        it('supports chained row calls', function()
            local kb = api.keyboard():row({'Button 1', 'Button 2'}):row({'Button 3'})
            assert.equals(2, #kb.keyboard)
        end)
    end)

    describe('inline_keyboard', function()
        it('creates an inline keyboard', function()
            local kb = api.inline_keyboard()
            assert.is_table(kb)
            assert.is_table(kb.inline_keyboard)
        end)

        it('supports chained row builder calls', function()
            local kb = api.inline_keyboard()
                :row(api.row():callback_data_button('Click', 'data1'))
                :row(api.row():url_button('Visit', 'https://example.com'))
            assert.equals(2, #kb.inline_keyboard)
        end)
    end)

    describe('row', function()
        it('creates an empty row', function()
            local r = api.row()
            assert.is_table(r)
            assert.equals(0, #r)
        end)

        it('supports callback_data_button', function()
            local r = api.row():callback_data_button('Click', 'data')
            assert.equals(1, #r)
            assert.equals('Click', r[1].text)
            assert.equals('data', r[1].callback_data)
        end)

        it('supports url_button', function()
            local r = api.row():url_button('Visit', 'https://example.com')
            assert.equals(1, #r)
            assert.equals('Visit', r[1].text)
            assert.equals('https://example.com', r[1].url)
        end)

        it('supports chaining multiple buttons', function()
            local r = api.row()
                :callback_data_button('A', 'a')
                :callback_data_button('B', 'b')
                :url_button('C', 'https://c.com')
            assert.equals(3, #r)
        end)

        it('supports switch_inline_query_button', function()
            local r = api.row():switch_inline_query_button('Search', 'query')
            assert.equals('query', r[1].switch_inline_query)
        end)

        it('supports pay_button', function()
            local r = api.row():pay_button('Pay', true)
            assert.is_true(r[1].pay)
        end)
    end)

    describe('standalone button constructors', function()
        it('url_button returns table', function()
            local btn = api.url_button('Click', 'https://example.com')
            assert.equals('Click', btn.text)
            assert.equals('https://example.com', btn.url)
        end)

        it('url_button returns false for missing params', function()
            assert.is_false(api.url_button(nil, 'url'))
            assert.is_false(api.url_button('text', nil))
        end)

        it('url_button returns JSON when encoded', function()
            local btn = api.url_button('Click', 'https://example.com', true)
            assert.is_string(btn)
            local decoded = json.decode(btn)
            assert.equals('Click', decoded.text)
        end)

        it('callback_data_button works', function()
            local btn = api.callback_data_button('Click', 'data')
            assert.equals('data', btn.callback_data)
        end)
    end)

    describe('remove_keyboard', function()
        it('creates remove keyboard markup', function()
            local rm = api.remove_keyboard()
            assert.is_true(rm.remove_keyboard)
            assert.is_false(rm.selective)
        end)

        it('supports selective', function()
            local rm = api.remove_keyboard(true)
            assert.is_true(rm.selective)
        end)
    end)

    describe('prices', function()
        it('creates price list with chaining', function()
            local p = api.prices()
                :labeled_price('Item 1', 100)
                :labeled_price('Item 2', 200)
            assert.equals(2, #p)
            assert.equals('Item 1', p[1].label)
            assert.equals(100, p[1].amount)
        end)
    end)

    describe('labeled_price', function()
        it('creates a labeled price', function()
            local lp = api.labeled_price('Test', 500)
            assert.equals('Test', lp.label)
            assert.equals(500, lp.amount)
        end)

        it('returns false for invalid amount', function()
            assert.is_false(api.labeled_price('Test', 'abc'))
        end)
    end)

    describe('chat_permissions', function()
        it('creates permissions with defaults', function()
            local p = api.chat_permissions()
            assert.is_table(p)
            assert.is_nil(p.can_send_messages)
        end)

        it('creates permissions with specified values', function()
            local p = api.chat_permissions({ can_send_messages = true, can_send_photos = true })
            assert.is_true(p.can_send_messages)
            assert.is_true(p.can_send_photos)
        end)
    end)

    describe('chat_administrator_rights', function()
        it('includes can_manage_direct_messages', function()
            local r = api.chat_administrator_rights({ can_manage_direct_messages = true })
            assert.is_true(r.can_manage_direct_messages)
        end)
    end)

    describe('bot_command', function()
        it('creates a bot command', function()
            local cmd = api.bot_command('start', 'Start the bot')
            assert.equals('start', cmd.command)
            assert.equals('Start the bot', cmd.description)
        end)

        it('truncates long commands', function()
            local cmd = api.bot_command(string.rep('a', 64), 'desc')
            assert.equals(32, #cmd.command)
        end)

        it('truncates long descriptions', function()
            local cmd = api.bot_command('cmd', string.rep('a', 512))
            assert.equals(256, #cmd.description)
        end)
    end)

    describe('inline_result', function()
        it('creates chainable inline result', function()
            local r = api.inline_result()
                :type('article')
                :id('1')
                :title('Test')
                :description('A test')
            assert.equals('article', r.type)
            assert.equals('1', r.id)
            assert.equals('Test', r.title)
            assert.equals('A test', r.description)
        end)

        it('supports all media fields', function()
            local r = api.inline_result()
                :photo_url('https://example.com/photo.jpg')
                :photo_width(800)
                :photo_height(600)
                :thumbnail_url('https://example.com/thumb.jpg')
            assert.equals('https://example.com/photo.jpg', r.photo_url)
            assert.equals(800, r.photo_width)
            assert.equals(600, r.photo_height)
            assert.equals('https://example.com/thumb.jpg', r.thumbnail_url)
        end)
    end)

    describe('input_text_message_content', function()
        it('creates text message content', function()
            local c = api.input_text_message_content('Hello', 'HTML')
            assert.equals('Hello', c.message_text)
            assert.equals('HTML', c.parse_mode)
        end)

        it('converts boolean true to markdown', function()
            local c = api.input_text_message_content('Hello', true)
            assert.equals('markdown', c.parse_mode)
        end)
    end)

    describe('reaction_type constructors', function()
        it('creates emoji reaction', function()
            local r = api.reaction_type_emoji('👍')
            assert.equals('emoji', r.type)
            assert.equals('👍', r.emoji)
        end)

        it('creates custom emoji reaction', function()
            local r = api.reaction_type_custom_emoji('12345')
            assert.equals('custom_emoji', r.type)
            assert.equals('12345', r.custom_emoji_id)
        end)
    end)

    describe('reply_parameters', function()
        it('creates reply parameters', function()
            local r = api.reply_parameters(42, 123, true)
            assert.equals(42, r.message_id)
            assert.equals(123, r.chat_id)
            assert.is_true(r.allow_sending_without_reply)
        end)
    end)

    describe('passport element error constructors', function()
        it('creates data field error', function()
            local e = api.passport_element_error_data_field('personal_details', 'first_name', 'abc123', 'Invalid')
            assert.equals('data', e.source)
            assert.equals('personal_details', e.type)
            assert.equals('first_name', e.field_name)
        end)

        it('creates front side error', function()
            local e = api.passport_element_error_front_side('passport', 'hash123', 'Blurry')
            assert.equals('front_side', e.source)
        end)

        it('creates unspecified error', function()
            local e = api.passport_element_error_unspecified('passport', 'hash', 'Error')
            assert.equals('unspecified', e.source)
        end)
    end)
end)
