local api = require('spec.test_helper')
local json = require('dkjson')

describe('legacy compatibility', function()
    before_each(function()
        api._clear_requests()
    end)

    describe('require paths', function()
        it('telegram-bot-lua.core returns api', function()
            local core = require('telegram-bot-lua.core')
            assert.is_table(core)
            assert.equals(api.version, core.version)
        end)
    end)

    describe('deprecated method names', function()
        it('get_chat_members_count forwards to get_chat_member_count', function()
            api.get_chat_members_count(123)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getChatMemberCount'))
        end)

        it('kick_chat_member forwards to ban_chat_member', function()
            api.kick_chat_member(123, 456, 1234567890)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/banChatMember'))
            assert.equals(1234567890, req.parameters.until_date)
        end)
    end)

    describe('positional arg wrappers', function()
        it('send_message with positional parse_mode still works', function()
            api.send_message(123, 'Hello', 'HTML')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendMessage'))
            assert.equals('HTML', req.parameters.parse_mode)
        end)

        it('send_message with opts table works normally', function()
            api.send_message(123, 'Hello', { parse_mode = 'HTML' })
            local req = api._last_request()
            assert.equals('HTML', req.parameters.parse_mode)
        end)

        it('send_message with nil opts works', function()
            api.send_message(123, 'Hello')
            local req = api._last_request()
            assert.equals('Hello', req.parameters.text)
        end)

        it('answer_callback_query with positional text works', function()
            api.answer_callback_query('123', 'Alert text', true)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/answerCallbackQuery'))
            assert.equals('Alert text', req.parameters.text)
            assert.is_true(req.parameters.show_alert)
        end)

        it('answer_callback_query with opts table works', function()
            api.answer_callback_query('123', { text = 'Hello' })
            local req = api._last_request()
            assert.equals('Hello', req.parameters.text)
        end)

        it('edit_message_text with positional parse_mode works', function()
            api.edit_message_text(123, 42, 'Updated', 'HTML')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/editMessageText'))
            assert.equals('HTML', req.parameters.parse_mode)
        end)

        it('edit_message_text with opts table works', function()
            api.edit_message_text(123, 42, 'Updated', { parse_mode = 'HTML' })
            local req = api._last_request()
            assert.equals('HTML', req.parameters.parse_mode)
        end)
    end)
end)
