-- Coverage tests for src/methods/{bot,chat,checklists,forum,games,gifts,inline}.lua
local api = require('spec.test_helper')
local json = require('dkjson')

describe('coverage: methods part A', function()
    before_each(function()
        api._clear_requests()
    end)

    describe('bot methods', function()
        it('get_file requests /getFile with file_id', function()
            local ok, status = api.get_file('ABC-123')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getFile', 1, true))
            assert.equals('ABC-123', req.parameters.file_id)
            assert.is_true(ok.ok)
            assert.equals(200, status)
        end)

        it('set_my_commands encodes commands table and scope table', function()
            api.set_my_commands({{ command = 'start', description = 'Start' }}, {
                scope = { type = 'all_private_chats' },
                language_code = 'en'
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setMyCommands', 1, true))
            local commands = json.decode(req.parameters.commands)
            assert.equals('start', commands[1].command)
            local scope = json.decode(req.parameters.scope)
            assert.equals('all_private_chats', scope.type)
            assert.equals('en', req.parameters.language_code)
        end)

        it('set_my_commands passes pre-encoded string commands through without opts', function()
            api.set_my_commands('[{"command":"help"}]')
            local req = api._last_request()
            assert.equals('[{"command":"help"}]', req.parameters.commands)
            assert.is_nil(req.parameters.scope)
            assert.is_nil(req.parameters.language_code)
        end)

        it('delete_my_commands works without opts', function()
            api.delete_my_commands()
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/deleteMyCommands', 1, true))
            assert.is_nil(req.parameters.scope)
            assert.is_nil(req.parameters.language_code)
        end)

        it('delete_my_commands encodes scope table and passes language_code', function()
            api.delete_my_commands({ scope = { type = 'default' }, language_code = 'de' })
            local req = api._last_request()
            assert.equals('default', json.decode(req.parameters.scope).type)
            assert.equals('de', req.parameters.language_code)
        end)

        it('get_my_commands works without opts', function()
            local ok, status = api.get_my_commands()
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getMyCommands', 1, true))
            assert.is_nil(req.parameters.scope)
            assert.is_true(ok.ok)
            assert.equals(200, status)
        end)

        it('get_my_commands encodes scope table', function()
            api.get_my_commands({ scope = { type = 'all_group_chats' }, language_code = 'fr' })
            local req = api._last_request()
            assert.equals('all_group_chats', json.decode(req.parameters.scope).type)
            assert.equals('fr', req.parameters.language_code)
        end)

        it('set_my_name truncates the name to 64 characters', function()
            api.set_my_name(string.rep('x', 100), { language_code = 'en' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setMyName', 1, true))
            assert.equals(64, #req.parameters.name)
            assert.equals('en', req.parameters.language_code)
        end)

        it('set_my_name works without opts', function()
            api.set_my_name('MyBot')
            local req = api._last_request()
            assert.equals('MyBot', req.parameters.name)
            assert.is_nil(req.parameters.language_code)
        end)

        it('get_my_name works with and without opts', function()
            api.get_my_name()
            assert.is_nil(api._last_request().parameters.language_code)
            api.get_my_name({ language_code = 'es' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getMyName', 1, true))
            assert.equals('es', req.parameters.language_code)
        end)

        it('set_my_description truncates the description to 512 characters', function()
            api.set_my_description(string.rep('d', 600))
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setMyDescription', 1, true))
            assert.equals(512, #req.parameters.description)
        end)

        it('set_my_description passes language_code from opts', function()
            api.set_my_description('short', { language_code = 'it' })
            local req = api._last_request()
            assert.equals('short', req.parameters.description)
            assert.equals('it', req.parameters.language_code)
        end)

        it('get_my_description works with and without opts', function()
            api.get_my_description()
            assert.truthy(api._last_request().endpoint:find('/getMyDescription', 1, true))
            api.get_my_description({ language_code = 'pt' })
            assert.equals('pt', api._last_request().parameters.language_code)
        end)

        it('set_my_short_description truncates to 120 characters', function()
            api.set_my_short_description(string.rep('s', 200))
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setMyShortDescription', 1, true))
            assert.equals(120, #req.parameters.short_description)
        end)

        it('set_my_short_description passes language_code from opts', function()
            api.set_my_short_description('hi', { language_code = 'nl' })
            assert.equals('nl', api._last_request().parameters.language_code)
        end)

        it('get_my_short_description works with and without opts', function()
            api.get_my_short_description()
            assert.truthy(api._last_request().endpoint:find('/getMyShortDescription', 1, true))
            api.get_my_short_description({ language_code = 'ru' })
            assert.equals('ru', api._last_request().parameters.language_code)
        end)

        it('set_chat_menu_button encodes menu_button table', function()
            api.set_chat_menu_button({ chat_id = 42, menu_button = { type = 'commands' } })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setChatMenuButton', 1, true))
            assert.equals(42, req.parameters.chat_id)
            assert.equals('commands', json.decode(req.parameters.menu_button).type)
        end)

        it('set_chat_menu_button works without opts', function()
            api.set_chat_menu_button()
            local req = api._last_request()
            assert.is_nil(req.parameters.chat_id)
            assert.is_nil(req.parameters.menu_button)
        end)

        it('get_chat_menu_button works with and without opts', function()
            api.get_chat_menu_button()
            assert.truthy(api._last_request().endpoint:find('/getChatMenuButton', 1, true))
            api.get_chat_menu_button({ chat_id = 7 })
            assert.equals(7, api._last_request().parameters.chat_id)
        end)

        it('set_my_default_administrator_rights encodes rights table', function()
            api.set_my_default_administrator_rights({
                rights = { can_manage_chat = true },
                for_channels = true
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setMyDefaultAdministratorRights', 1, true))
            assert.is_true(json.decode(req.parameters.rights).can_manage_chat)
            assert.is_true(req.parameters.for_channels)
        end)

        it('set_my_default_administrator_rights works without opts', function()
            api.set_my_default_administrator_rights()
            local req = api._last_request()
            assert.is_nil(req.parameters.rights)
            assert.is_nil(req.parameters.for_channels)
        end)

        it('get_my_default_administrator_rights works with and without opts', function()
            api.get_my_default_administrator_rights()
            assert.truthy(api._last_request().endpoint:find('/getMyDefaultAdministratorRights', 1, true))
            api.get_my_default_administrator_rights({ for_channels = true })
            assert.is_true(api._last_request().parameters.for_channels)
        end)

        it('set_my_profile_photo sends photo as file payload', function()
            api.set_my_profile_photo({ photo = '/tmp/photo.png', is_public = true })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setMyProfilePhoto', 1, true))
            assert.is_true(req.parameters.is_public)
            assert.equals('/tmp/photo.png', req.file.photo)
        end)

        it('set_my_profile_photo works without opts', function()
            api.set_my_profile_photo()
            local req = api._last_request()
            assert.is_nil(req.parameters.is_public)
            assert.is_nil(req.file.photo)
        end)

        it('remove_my_profile_photo works with and without opts', function()
            api.remove_my_profile_photo()
            assert.truthy(api._last_request().endpoint:find('/removeMyProfilePhoto', 1, true))
            api.remove_my_profile_photo({ is_public = true })
            assert.is_true(api._last_request().parameters.is_public)
        end)

        it('get_managed_bot_token passes user_id', function()
            api.get_managed_bot_token(555)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getManagedBotToken', 1, true))
            assert.equals(555, req.parameters.user_id)
        end)

        it('replace_managed_bot_token passes user_id', function()
            api.replace_managed_bot_token(556)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/replaceManagedBotToken', 1, true))
            assert.equals(556, req.parameters.user_id)
        end)

        it('save_prepared_keyboard_button encodes the button table', function()
            api.save_prepared_keyboard_button(1, { text = 'Press', url = 'https://x.test' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/savePreparedKeyboardButton', 1, true))
            assert.equals(1, req.parameters.user_id)
            assert.equals('Press', json.decode(req.parameters.button).text)
        end)

        it('get_managed_bot_access_settings passes user_id', function()
            api.get_managed_bot_access_settings(777)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getManagedBotAccessSettings', 1, true))
            assert.equals(777, req.parameters.user_id)
        end)

        it('set_managed_bot_access_settings encodes added_user_ids', function()
            api.set_managed_bot_access_settings(777, true, { added_user_ids = { 1, 2, 3 } })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setManagedBotAccessSettings', 1, true))
            assert.equals(777, req.parameters.user_id)
            assert.is_true(req.parameters.is_access_restricted)
            assert.same({ 1, 2, 3 }, json.decode(req.parameters.added_user_ids))
        end)

        it('set_managed_bot_access_settings works without opts', function()
            api.set_managed_bot_access_settings(778, false)
            local req = api._last_request()
            assert.is_false(req.parameters.is_access_restricted)
            assert.is_nil(req.parameters.added_user_ids)
        end)

        it('get_user_personal_chat_messages passes user_id and limit', function()
            api.get_user_personal_chat_messages(9, 20)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getUserPersonalChatMessages', 1, true))
            assert.equals(9, req.parameters.user_id)
            assert.equals(20, req.parameters.limit)
        end)

        it('verify_user passes custom_description, works without opts', function()
            api.verify_user(11)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/verifyUser', 1, true))
            assert.equals(11, req.parameters.user_id)
            assert.is_nil(req.parameters.custom_description)
            api.verify_user(11, { custom_description = 'Trusted' })
            assert.equals('Trusted', api._last_request().parameters.custom_description)
        end)

        it('verify_chat passes custom_description, works without opts', function()
            api.verify_chat('@chan')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/verifyChat', 1, true))
            assert.equals('@chan', req.parameters.chat_id)
            api.verify_chat('@chan', { custom_description = 'Official' })
            assert.equals('Official', api._last_request().parameters.custom_description)
        end)

        it('remove_user_verification passes user_id', function()
            api.remove_user_verification(12)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/removeUserVerification', 1, true))
            assert.equals(12, req.parameters.user_id)
        end)

        it('remove_chat_verification passes chat_id', function()
            api.remove_chat_verification(-100123)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/removeChatVerification', 1, true))
            assert.equals(-100123, req.parameters.chat_id)
        end)

        it('set_user_emoji_status passes emoji status opts, works without opts', function()
            api.set_user_emoji_status(13)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setUserEmojiStatus', 1, true))
            assert.equals(13, req.parameters.user_id)
            assert.is_nil(req.parameters.emoji_status_custom_emoji_id)
            api.set_user_emoji_status(13, {
                emoji_status_custom_emoji_id = 'emoji_1',
                emoji_status_expiration_date = 1700000000
            })
            req = api._last_request()
            assert.equals('emoji_1', req.parameters.emoji_status_custom_emoji_id)
            assert.equals(1700000000, req.parameters.emoji_status_expiration_date)
        end)
    end)

    describe('chat methods', function()
        it('get_chat passes chat_id', function()
            api.get_chat('@group')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getChat', 1, true))
            assert.equals('@group', req.parameters.chat_id)
        end)

        it('get_chat_administrators passes return_bots, works without opts', function()
            api.get_chat_administrators(1)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getChatAdministrators', 1, true))
            assert.is_nil(req.parameters.return_bots)
            api.get_chat_administrators(1, { return_bots = true })
            assert.is_true(api._last_request().parameters.return_bots)
        end)

        it('get_chat_member_count passes chat_id', function()
            api.get_chat_member_count(2)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getChatMemberCount', 1, true))
            assert.equals(2, req.parameters.chat_id)
        end)

        it('get_chat_member passes chat_id and user_id', function()
            api.get_chat_member(3, 4)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getChatMember', 1, true))
            assert.equals(3, req.parameters.chat_id)
            assert.equals(4, req.parameters.user_id)
        end)

        it('leave_chat passes chat_id and returns the mock contract', function()
            local ok, status = api.leave_chat(5)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/leaveChat', 1, true))
            assert.equals(5, req.parameters.chat_id)
            assert.is_true(ok.ok)
            assert.equals(200, status)
        end)

        it('set_chat_title truncates title to 128 characters', function()
            api.set_chat_title(6, string.rep('t', 200))
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setChatTitle', 1, true))
            assert.equals(6, req.parameters.chat_id)
            assert.equals(128, #req.parameters.title)
        end)

        it('set_chat_description truncates description to 255 characters', function()
            api.set_chat_description(7, string.rep('d', 300))
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setChatDescription', 1, true))
            assert.equals(255, #req.parameters.description)
        end)

        it('set_chat_photo sends photo as file payload', function()
            api.set_chat_photo(8, '/tmp/chat.png')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setChatPhoto', 1, true))
            assert.equals(8, req.parameters.chat_id)
            assert.equals('/tmp/chat.png', req.file.photo)
        end)

        it('delete_chat_photo passes chat_id', function()
            api.delete_chat_photo(9)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/deleteChatPhoto', 1, true))
            assert.equals(9, req.parameters.chat_id)
        end)

        it('set_chat_permissions encodes permissions table', function()
            api.set_chat_permissions(10, { can_send_messages = false }, {
                use_independent_chat_permissions = true
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setChatPermissions', 1, true))
            assert.is_false(json.decode(req.parameters.permissions).can_send_messages)
            assert.is_true(req.parameters.use_independent_chat_permissions)
        end)

        it('set_chat_permissions accepts string permissions without opts', function()
            api.set_chat_permissions(10, '{"can_send_messages":true}')
            local req = api._last_request()
            assert.equals('{"can_send_messages":true}', req.parameters.permissions)
            assert.is_nil(req.parameters.use_independent_chat_permissions)
        end)

        it('set_chat_sticker_set passes sticker_set_name', function()
            api.set_chat_sticker_set(11, 'my_pack')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setChatStickerSet', 1, true))
            assert.equals('my_pack', req.parameters.sticker_set_name)
        end)

        it('delete_chat_sticker_set passes chat_id', function()
            api.delete_chat_sticker_set(12)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/deleteChatStickerSet', 1, true))
            assert.equals(12, req.parameters.chat_id)
        end)

        it('pin_chat_message passes opts, works without opts', function()
            api.pin_chat_message(13, 100)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/pinChatMessage', 1, true))
            assert.equals(100, req.parameters.message_id)
            assert.is_nil(req.parameters.disable_notification)
            api.pin_chat_message(13, 100, {
                disable_notification = true,
                business_connection_id = 'biz1'
            })
            req = api._last_request()
            assert.is_true(req.parameters.disable_notification)
            assert.equals('biz1', req.parameters.business_connection_id)
        end)

        it('unpin_chat_message passes opts, works without opts', function()
            api.unpin_chat_message(14)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/unpinChatMessage', 1, true))
            assert.equals(14, req.parameters.chat_id)
            assert.is_nil(req.parameters.message_id)
            api.unpin_chat_message(14, { message_id = 101, business_connection_id = 'biz2' })
            req = api._last_request()
            assert.equals(101, req.parameters.message_id)
            assert.equals('biz2', req.parameters.business_connection_id)
        end)

        it('unpin_all_chat_messages passes chat_id', function()
            api.unpin_all_chat_messages(15)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/unpinAllChatMessages', 1, true))
            assert.equals(15, req.parameters.chat_id)
        end)

        it('export_chat_invite_link passes chat_id', function()
            api.export_chat_invite_link(16)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/exportChatInviteLink', 1, true))
            assert.equals(16, req.parameters.chat_id)
        end)

        it('create_chat_invite_link passes opts, works without opts', function()
            api.create_chat_invite_link(17)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/createChatInviteLink', 1, true))
            assert.is_nil(req.parameters.name)
            api.create_chat_invite_link(17, {
                name = 'Friends',
                expire_date = 1700000001,
                member_limit = 5,
                creates_join_request = true
            })
            req = api._last_request()
            assert.equals('Friends', req.parameters.name)
            assert.equals(1700000001, req.parameters.expire_date)
            assert.equals(5, req.parameters.member_limit)
            assert.is_true(req.parameters.creates_join_request)
        end)

        it('edit_chat_invite_link passes invite_link and opts, works without opts', function()
            api.edit_chat_invite_link(18, 'https://t.me/+abc')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/editChatInviteLink', 1, true))
            assert.equals('https://t.me/+abc', req.parameters.invite_link)
            api.edit_chat_invite_link(18, 'https://t.me/+abc', { name = 'VIP', member_limit = 2 })
            req = api._last_request()
            assert.equals('VIP', req.parameters.name)
            assert.equals(2, req.parameters.member_limit)
        end)

        it('revoke_chat_invite_link passes invite_link', function()
            api.revoke_chat_invite_link(19, 'https://t.me/+rev')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/revokeChatInviteLink', 1, true))
            assert.equals('https://t.me/+rev', req.parameters.invite_link)
        end)

        it('approve_chat_join_request passes chat_id and user_id', function()
            api.approve_chat_join_request(20, 21)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/approveChatJoinRequest', 1, true))
            assert.equals(20, req.parameters.chat_id)
            assert.equals(21, req.parameters.user_id)
        end)

        it('decline_chat_join_request passes chat_id and user_id', function()
            api.decline_chat_join_request(22, 23)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/declineChatJoinRequest', 1, true))
            assert.equals(22, req.parameters.chat_id)
            assert.equals(23, req.parameters.user_id)
        end)

        it('get_user_chat_boosts passes chat_id and user_id', function()
            api.get_user_chat_boosts(24, 25)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getUserChatBoosts', 1, true))
            assert.equals(24, req.parameters.chat_id)
            assert.equals(25, req.parameters.user_id)
        end)

        it('answer_chat_join_request_query passes query id and result', function()
            api.answer_chat_join_request_query('q1', 'approve')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/answerChatJoinRequestQuery', 1, true))
            assert.equals('q1', req.parameters.chat_join_request_query_id)
            assert.equals('approve', req.parameters.result)
        end)

        it('send_chat_join_request_web_app passes query id and web app url', function()
            api.send_chat_join_request_web_app('q2', 'https://app.test')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendChatJoinRequestWebApp', 1, true))
            assert.equals('q2', req.parameters.chat_join_request_query_id)
            assert.equals('https://app.test', req.parameters.web_app_url)
        end)

        it('create_chat_subscription_invite_link passes period, price and name', function()
            api.create_chat_subscription_invite_link(26, 2592000, 10, { name = 'Sub' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/createChatSubscriptionInviteLink', 1, true))
            assert.equals(2592000, req.parameters.subscription_period)
            assert.equals(10, req.parameters.subscription_price)
            assert.equals('Sub', req.parameters.name)
        end)

        it('create_chat_subscription_invite_link works without opts', function()
            api.create_chat_subscription_invite_link(26, 2592000, 10)
            assert.is_nil(api._last_request().parameters.name)
        end)

        it('edit_chat_subscription_invite_link passes invite_link and name', function()
            api.edit_chat_subscription_invite_link(27, 'https://t.me/+sub', { name = 'NewName' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/editChatSubscriptionInviteLink', 1, true))
            assert.equals('https://t.me/+sub', req.parameters.invite_link)
            assert.equals('NewName', req.parameters.name)
        end)

        it('edit_chat_subscription_invite_link works without opts', function()
            api.edit_chat_subscription_invite_link(27, 'https://t.me/+sub')
            assert.is_nil(api._last_request().parameters.name)
        end)
    end)

    describe('checklists methods', function()
        it('send_checklist encodes checklist, reply_parameters and reply_markup tables', function()
            api.send_checklist(1, { title = 'Todo', tasks = {{ id = 1, text = 'a' }} }, {
                disable_notification = true,
                protect_content = true,
                reply_parameters = { message_id = 5 },
                reply_markup = { inline_keyboard = {} }
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendChecklist', 1, true))
            assert.equals(1, req.parameters.chat_id)
            assert.equals('Todo', json.decode(req.parameters.checklist).title)
            assert.is_true(req.parameters.disable_notification)
            assert.is_true(req.parameters.protect_content)
            assert.equals(5, json.decode(req.parameters.reply_parameters).message_id)
            assert.is_table(json.decode(req.parameters.reply_markup).inline_keyboard)
        end)

        it('send_checklist accepts pre-encoded string checklist without opts', function()
            api.send_checklist(1, '{"title":"Raw"}')
            local req = api._last_request()
            assert.equals('{"title":"Raw"}', req.parameters.checklist)
            assert.is_nil(req.parameters.reply_parameters)
            assert.is_nil(req.parameters.reply_markup)
        end)

        it('edit_checklist passes task id, text and is_completed', function()
            api.edit_checklist(2, 30, 'task_1', { text = 'updated', is_completed = true })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/editChecklist', 1, true))
            assert.equals(2, req.parameters.chat_id)
            assert.equals(30, req.parameters.message_id)
            assert.equals('task_1', req.parameters.checklist_task_id)
            assert.equals('updated', req.parameters.text)
            assert.is_true(req.parameters.is_completed)
        end)

        it('edit_checklist works without opts', function()
            api.edit_checklist(2, 30, 'task_2')
            local req = api._last_request()
            assert.equals('task_2', req.parameters.checklist_task_id)
            assert.is_nil(req.parameters.text)
            assert.is_nil(req.parameters.is_completed)
        end)

        it('add_checklist_tasks encodes tasks table', function()
            api.add_checklist_tasks(3, 31, {{ id = 2, text = 'new task' }})
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/addChecklistTasks', 1, true))
            assert.equals(3, req.parameters.chat_id)
            assert.equals(31, req.parameters.message_id)
            assert.equals('new task', json.decode(req.parameters.tasks)[1].text)
        end)

        it('edit_message_checklist encodes checklist and reply_markup', function()
            api.edit_message_checklist('biz9', 4, 32, { title = 'C' }, {
                reply_markup = { inline_keyboard = {} }
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/editMessageChecklist', 1, true))
            assert.equals('biz9', req.parameters.business_connection_id)
            assert.equals(4, req.parameters.chat_id)
            assert.equals(32, req.parameters.message_id)
            assert.equals('C', json.decode(req.parameters.checklist).title)
            assert.is_table(json.decode(req.parameters.reply_markup).inline_keyboard)
        end)

        it('edit_message_checklist works without opts', function()
            api.edit_message_checklist('biz9', 4, 33, '{"title":"S"}')
            local req = api._last_request()
            assert.equals('{"title":"S"}', req.parameters.checklist)
            assert.is_nil(req.parameters.reply_markup)
        end)
    end)

    describe('forum methods', function()
        it('get_forum_topic_icon_stickers requests the endpoint with no parameters', function()
            local ok, status = api.get_forum_topic_icon_stickers()
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getForumTopicIconStickers', 1, true))
            assert.is_nil(req.parameters)
            assert.is_true(ok.ok)
            assert.equals(200, status)
        end)

        it('create_forum_topic truncates name to 128 and passes icon opts', function()
            api.create_forum_topic(1, string.rep('n', 200), {
                icon_color = 0x6FB9F0,
                icon_custom_emoji_id = 'em1'
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/createForumTopic', 1, true))
            assert.equals(128, #req.parameters.name)
            assert.equals(0x6FB9F0, req.parameters.icon_color)
            assert.equals('em1', req.parameters.icon_custom_emoji_id)
        end)

        it('create_forum_topic works without opts', function()
            api.create_forum_topic(1, 'General chat')
            local req = api._last_request()
            assert.equals('General chat', req.parameters.name)
            assert.is_nil(req.parameters.icon_color)
        end)

        it('edit_forum_topic passes name and emoji, works without opts', function()
            api.edit_forum_topic(2, 55)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/editForumTopic', 1, true))
            assert.equals(55, req.parameters.message_thread_id)
            assert.is_nil(req.parameters.name)
            api.edit_forum_topic(2, 55, { name = 'Renamed', icon_custom_emoji_id = 'em2' })
            req = api._last_request()
            assert.equals('Renamed', req.parameters.name)
            assert.equals('em2', req.parameters.icon_custom_emoji_id)
        end)

        it('close_forum_topic passes chat_id and message_thread_id', function()
            api.close_forum_topic(3, 56)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/closeForumTopic', 1, true))
            assert.equals(3, req.parameters.chat_id)
            assert.equals(56, req.parameters.message_thread_id)
        end)

        it('reopen_forum_topic passes chat_id and message_thread_id', function()
            api.reopen_forum_topic(4, 57)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/reopenForumTopic', 1, true))
            assert.equals(57, req.parameters.message_thread_id)
        end)

        it('delete_forum_topic passes chat_id and message_thread_id', function()
            api.delete_forum_topic(5, 58)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/deleteForumTopic', 1, true))
            assert.equals(58, req.parameters.message_thread_id)
        end)

        it('unpin_all_forum_topic_messages passes chat_id and message_thread_id', function()
            api.unpin_all_forum_topic_messages(6, 59)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/unpinAllForumTopicMessages', 1, true))
            assert.equals(59, req.parameters.message_thread_id)
        end)

        it('edit_general_forum_topic truncates name to 128', function()
            api.edit_general_forum_topic(7, string.rep('g', 130))
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/editGeneralForumTopic', 1, true))
            assert.equals(7, req.parameters.chat_id)
            assert.equals(128, #req.parameters.name)
        end)

        it('close_general_forum_topic passes chat_id', function()
            api.close_general_forum_topic(8)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/closeGeneralForumTopic', 1, true))
            assert.equals(8, req.parameters.chat_id)
        end)

        it('reopen_general_forum_topic passes chat_id', function()
            api.reopen_general_forum_topic(9)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/reopenGeneralForumTopic', 1, true))
            assert.equals(9, req.parameters.chat_id)
        end)

        it('hide_general_forum_topic passes chat_id', function()
            api.hide_general_forum_topic(10)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/hideGeneralForumTopic', 1, true))
            assert.equals(10, req.parameters.chat_id)
        end)

        it('unhide_general_forum_topic passes chat_id', function()
            api.unhide_general_forum_topic(11)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/unhideGeneralForumTopic', 1, true))
            assert.equals(11, req.parameters.chat_id)
        end)

        it('unpin_all_general_forum_topic_messages passes chat_id', function()
            api.unpin_all_general_forum_topic_messages(12)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/unpinAllGeneralForumTopicMessages', 1, true))
            assert.equals(12, req.parameters.chat_id)
        end)
    end)

    describe('games methods', function()
        it('send_game encodes reply_parameters and reply_markup and passes opts', function()
            api.send_game(1, 'tetris', {
                message_thread_id = 9,
                disable_notification = true,
                protect_content = true,
                reply_parameters = { message_id = 3 },
                reply_markup = { inline_keyboard = {} },
                business_connection_id = 'biz3',
                message_effect_id = 'fx',
                allow_paid_broadcast = true
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendGame', 1, true))
            assert.equals(1, req.parameters.chat_id)
            assert.equals('tetris', req.parameters.game_short_name)
            assert.equals(9, req.parameters.message_thread_id)
            assert.is_true(req.parameters.disable_notification)
            assert.is_true(req.parameters.protect_content)
            assert.equals(3, json.decode(req.parameters.reply_parameters).message_id)
            assert.is_table(json.decode(req.parameters.reply_markup).inline_keyboard)
            assert.equals('biz3', req.parameters.business_connection_id)
            assert.equals('fx', req.parameters.message_effect_id)
            assert.is_true(req.parameters.allow_paid_broadcast)
        end)

        it('send_game works without opts', function()
            api.send_game(1, 'snake')
            local req = api._last_request()
            assert.equals('snake', req.parameters.game_short_name)
            assert.is_nil(req.parameters.reply_parameters)
            assert.is_nil(req.parameters.reply_markup)
        end)

        it('set_game_score passes score and opts, works without opts', function()
            api.set_game_score(2, 42)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setGameScore', 1, true))
            assert.equals(2, req.parameters.user_id)
            assert.equals(42, req.parameters.score)
            assert.is_nil(req.parameters.force)
            api.set_game_score(2, 42, {
                force = true,
                disable_edit_message = true,
                chat_id = 5,
                message_id = 6,
                inline_message_id = 'im1'
            })
            req = api._last_request()
            assert.is_true(req.parameters.force)
            assert.is_true(req.parameters.disable_edit_message)
            assert.equals(5, req.parameters.chat_id)
            assert.equals(6, req.parameters.message_id)
            assert.equals('im1', req.parameters.inline_message_id)
        end)

        it('get_game_high_scores passes opts, works without opts', function()
            api.get_game_high_scores(3)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getGameHighScores', 1, true))
            assert.equals(3, req.parameters.user_id)
            assert.is_nil(req.parameters.chat_id)
            api.get_game_high_scores(3, { chat_id = 7, message_id = 8, inline_message_id = 'im2' })
            req = api._last_request()
            assert.equals(7, req.parameters.chat_id)
            assert.equals(8, req.parameters.message_id)
            assert.equals('im2', req.parameters.inline_message_id)
        end)
    end)

    describe('gifts methods', function()
        it('get_user_gifts passes user_id', function()
            api.get_user_gifts(1)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getUserGifts', 1, true))
            assert.equals(1, req.parameters.user_id)
        end)

        it('get_available_gifts requests the endpoint with no parameters', function()
            local ok, status = api.get_available_gifts()
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getAvailableGifts', 1, true))
            assert.is_nil(req.parameters)
            assert.is_true(ok.ok)
            assert.equals(200, status)
        end)

        it('send_gift passes gift_id and opts, works without opts', function()
            api.send_gift(2, 'gift_1')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendGift', 1, true))
            assert.equals(2, req.parameters.user_id)
            assert.equals('gift_1', req.parameters.gift_id)
            assert.is_nil(req.parameters.text)
            api.send_gift(2, 'gift_1', {
                text = 'Congrats',
                text_parse_mode = 'HTML',
                pay_for_upgrade = true
            })
            req = api._last_request()
            assert.equals('Congrats', req.parameters.text)
            assert.equals('HTML', req.parameters.text_parse_mode)
            assert.is_true(req.parameters.pay_for_upgrade)
        end)

        it('transfer_gift passes star_count, works without opts', function()
            api.transfer_gift('biz4', 'owned_1', 3)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/transferGift', 1, true))
            assert.equals('biz4', req.parameters.business_connection_id)
            assert.equals('owned_1', req.parameters.owned_gift_id)
            assert.equals(3, req.parameters.new_owner_chat_id)
            assert.is_nil(req.parameters.star_count)
            api.transfer_gift('biz4', 'owned_1', 3, { star_count = 25 })
            assert.equals(25, api._last_request().parameters.star_count)
        end)

        it('upgrade_gift passes opts, works without opts', function()
            api.upgrade_gift('biz5', 'owned_2')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/upgradeGift', 1, true))
            assert.equals('owned_2', req.parameters.owned_gift_id)
            assert.is_nil(req.parameters.keep_original_details)
            api.upgrade_gift('biz5', 'owned_2', { keep_original_details = true, star_count = 50 })
            req = api._last_request()
            assert.is_true(req.parameters.keep_original_details)
            assert.equals(50, req.parameters.star_count)
        end)

        it('convert_gift_to_stars passes connection and gift ids', function()
            api.convert_gift_to_stars('biz6', 'owned_3')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/convertGiftToStars', 1, true))
            assert.equals('biz6', req.parameters.business_connection_id)
            assert.equals('owned_3', req.parameters.owned_gift_id)
        end)

        it('gift_premium_subscription encodes text_entities, works without opts', function()
            api.gift_premium_subscription(4, 3, 1000)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/giftPremiumSubscription', 1, true))
            assert.equals(4, req.parameters.user_id)
            assert.equals(3, req.parameters.month_count)
            assert.equals(1000, req.parameters.star_count)
            assert.is_nil(req.parameters.text_entities)
            api.gift_premium_subscription(4, 6, 2000, {
                text = 'Enjoy',
                text_parse_mode = 'HTML',
                text_entities = {{ type = 'bold', offset = 0, length = 5 }}
            })
            req = api._last_request()
            assert.equals('Enjoy', req.parameters.text)
            assert.equals('HTML', req.parameters.text_parse_mode)
            assert.equals('bold', json.decode(req.parameters.text_entities)[1].type)
        end)
    end)

    describe('inline methods', function()
        it('answer_inline_query wraps a single result table (with id) into an array', function()
            api.answer_inline_query('iq1', { id = '5', type = 'article', title = 'T' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/answerInlineQuery', 1, true))
            assert.equals('iq1', req.parameters.inline_query_id)
            local results = json.decode(req.parameters.results)
            assert.equals(1, #results)
            assert.equals('5', results[1].id)
        end)

        it('answer_inline_query encodes an array of results as-is', function()
            api.answer_inline_query('iq2', {
                { id = '1', type = 'article', title = 'A' },
                { id = '2', type = 'article', title = 'B' }
            })
            local results = json.decode(api._last_request().parameters.results)
            assert.equals(2, #results)
            assert.equals('B', results[2].title)
        end)

        it('answer_inline_query passes string results through and encodes button', function()
            api.answer_inline_query('iq3', '[]', {
                cache_time = 30,
                is_personal = true,
                next_offset = '10',
                button = { text = 'Go', start_parameter = 'x' }
            })
            local req = api._last_request()
            assert.equals('[]', req.parameters.results)
            assert.equals(30, req.parameters.cache_time)
            assert.is_true(req.parameters.is_personal)
            assert.equals('10', req.parameters.next_offset)
            assert.equals('Go', json.decode(req.parameters.button).text)
        end)

        it('answer_web_app_query encodes a table result', function()
            api.answer_web_app_query('waq1', { type = 'article', id = '1', title = 'W' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/answerWebAppQuery', 1, true))
            assert.equals('waq1', req.parameters.web_app_query_id)
            assert.equals('W', json.decode(req.parameters.result).title)
        end)

        it('answer_guest_query encodes a table result', function()
            api.answer_guest_query('gq1', { type = 'article', id = '1', title = 'G' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/answerGuestQuery', 1, true))
            assert.equals('gq1', req.parameters.guest_query_id)
            assert.equals('G', json.decode(req.parameters.result).title)
        end)

        it('answer_callback_query passes opts, works without opts', function()
            api.answer_callback_query('cbq1')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/answerCallbackQuery', 1, true))
            assert.equals('cbq1', req.parameters.callback_query_id)
            assert.is_nil(req.parameters.text)
            api.answer_callback_query('cbq1', {
                text = 'Done',
                show_alert = true,
                url = 'https://cb.test',
                cache_time = 60
            })
            req = api._last_request()
            assert.equals('Done', req.parameters.text)
            assert.is_true(req.parameters.show_alert)
            assert.equals('https://cb.test', req.parameters.url)
            assert.equals(60, req.parameters.cache_time)
        end)

        it('send_inline_article defaults description and message_text from title', function()
            api.send_inline_article('iq4', 'Title only')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/answerInlineQuery', 1, true))
            local results = json.decode(req.parameters.results)
            assert.equals('article', results[1].type)
            assert.equals('Title only', results[1].title)
            assert.equals('Title only', results[1].description)
            assert.equals('Title only', results[1].input_message_content.message_text)
        end)

        it('send_inline_article maps parse_mode=true to MarkdownV2', function()
            api.send_inline_article('iq5', 'T', 'D', '*msg*', true)
            local results = json.decode(api._last_request().parameters.results)
            assert.equals('MarkdownV2', results[1].input_message_content.parse_mode)
            assert.equals('*msg*', results[1].input_message_content.message_text)
        end)

        it('send_inline_article keeps a string parse_mode', function()
            api.send_inline_article('iq6', 'T', 'D', '<b>m</b>', 'HTML')
            local results = json.decode(api._last_request().parameters.results)
            assert.equals('HTML', results[1].input_message_content.parse_mode)
        end)

        it('send_inline_article_url uses numeric id and hide_url default', function()
            api.send_inline_article_url('iq7', 'T', 'https://l.test', nil, nil, nil, 7)
            local results = json.decode(api._last_request().parameters.results)
            assert.equals('7', results[1].id)
            assert.equals('https://l.test', results[1].url)
            assert.is_false(results[1].hide_url)
        end)

        it('send_inline_article_url falls back to id "1" for non-numeric id', function()
            api.send_inline_article_url('iq8', 'T', 'https://l.test', true, {
                message_text = 'body'
            })
            local results = json.decode(api._last_request().parameters.results)
            assert.equals('1', results[1].id)
            assert.is_true(results[1].hide_url)
            assert.equals('body', results[1].input_message_content.message_text)
        end)

        it('send_inline_photo builds a photo result with thumbnail from the url', function()
            api.send_inline_photo('iq9', 'https://p.test/x.jpg', 'cap')
            local results = json.decode(api._last_request().parameters.results)
            assert.equals('photo', results[1].type)
            assert.equals('https://p.test/x.jpg', results[1].photo_url)
            assert.equals('https://p.test/x.jpg', results[1].thumbnail_url)
            assert.equals('cap', results[1].caption)
        end)

        it('send_inline_cached_photo builds a cached photo result', function()
            api.send_inline_cached_photo('iq10', 'file_1', 'cap2')
            local results = json.decode(api._last_request().parameters.results)
            assert.equals('photo', results[1].type)
            assert.equals('file_1', results[1].photo_file_id)
            assert.equals('cap2', results[1].caption)
        end)

        it('save_prepared_inline_message encodes result and passes allow flags', function()
            api.save_prepared_inline_message(1, { type = 'article', id = '1', title = 'P' }, {
                allow_user_chats = true,
                allow_bot_chats = false,
                allow_group_chats = true,
                allow_channel_chats = false
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/savePreparedInlineMessage', 1, true))
            assert.equals(1, req.parameters.user_id)
            assert.equals('P', json.decode(req.parameters.result).title)
            assert.is_true(req.parameters.allow_user_chats)
            assert.is_false(req.parameters.allow_bot_chats)
            assert.is_true(req.parameters.allow_group_chats)
            assert.is_false(req.parameters.allow_channel_chats)
        end)

        it('save_prepared_inline_message works without opts', function()
            api.save_prepared_inline_message(1, '{"type":"article"}')
            local req = api._last_request()
            assert.equals('{"type":"article"}', req.parameters.result)
            assert.is_nil(req.parameters.allow_user_chats)
        end)
    end)
end)
