local api = require('spec.test_helper')
local json = require('dkjson')

describe('methods', function()
    before_each(function()
        api._clear_requests()
    end)

    describe('messages', function()
        it('send_message sends to correct endpoint', function()
            api.send_message(123, 'Hello')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendMessage'))
            assert.equals(123, req.parameters.chat_id)
            assert.equals('Hello', req.parameters.text)
        end)

        it('send_message accepts message table as chat_id', function()
            api.send_message({ chat = { id = 456 }}, 'Hello')
            local req = api._last_request()
            assert.equals(456, req.parameters.chat_id)
        end)

        it('send_message passes opts', function()
            api.send_message(123, 'Hello', {
                parse_mode = 'HTML',
                disable_notification = true
            })
            local req = api._last_request()
            assert.equals('HTML', req.parameters.parse_mode)
            assert.is_true(req.parameters.disable_notification)
        end)

        it('send_message converts boolean parse_mode', function()
            api.send_message(123, 'Hello', { parse_mode = true })
            local req = api._last_request()
            assert.equals('MarkdownV2', req.parameters.parse_mode)
        end)

        it('send_message JSON-encodes reply_markup', function()
            local kb = api.inline_keyboard():row(api.row():callback_data_button('A', 'a'))
            api.send_message(123, 'Hello', { reply_markup = kb })
            local req = api._last_request()
            local decoded = json.decode(req.parameters.reply_markup)
            assert.is_table(decoded.inline_keyboard)
        end)

        it('send_reply validates message table', function()
            local result = api.send_reply('not a table', 'text')
            assert.is_false(result)
        end)

        it('send_reply creates reply_parameters', function()
            api.send_reply({ chat = { id = 123 }, message_id = 42 }, 'Hello')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendMessage'))
            local rp = json.decode(req.parameters.reply_parameters)
            assert.equals(42, rp.message_id)
        end)

        it('forward_message works', function()
            api.forward_message(123, 456, 789)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/forwardMessage'))
            assert.equals(789, req.parameters.message_id)
        end)

        it('copy_message works', function()
            api.copy_message(123, 456, 789, { caption = 'New caption' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/copyMessage'))
            assert.equals('New caption', req.parameters.caption)
        end)

        it('send_photo passes file param', function()
            api.send_photo(123, 'photo_file_id')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendPhoto'))
            assert.is_table(req.file)
            assert.equals('photo_file_id', req.file.photo)
        end)

        it('send_document passes file param', function()
            api.send_document(123, 'doc_id')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendDocument'))
        end)

        it('send_poll encodes options', function()
            api.send_poll(123, 'Question?', {
                { text = 'Yes' }, { text = 'No' }
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendPoll'))
            local opts = json.decode(req.parameters.options)
            assert.equals(2, #opts)
        end)

        it('send_dice works', function()
            api.send_dice(123, { emoji = '🎲' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendDice'))
        end)

        it('send_chat_action works', function()
            api.send_chat_action(123, 'typing')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendChatAction'))
            assert.equals('typing', req.parameters.action)
        end)

        it('send_paid_media works', function()
            api.send_paid_media(123, 100, {})
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendPaidMedia'))
            assert.equals(100, req.parameters.star_count)
        end)

        it('edit_message_text works', function()
            api.edit_message_text(123, 42, 'Updated', { parse_mode = 'HTML' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/editMessageText'))
            assert.equals('Updated', req.parameters.text)
            assert.equals('HTML', req.parameters.parse_mode)
        end)

        it('delete_message works', function()
            api.delete_message(123, 42)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/deleteMessage'))
        end)

        it('delete_messages encodes message_ids', function()
            api.delete_messages(123, {1, 2, 3})
            local req = api._last_request()
            local ids = json.decode(req.parameters.message_ids)
            assert.equals(3, #ids)
        end)
    end)

    describe('chat', function()
        it('get_chat works', function()
            api.get_chat(123)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getChat'))
        end)

        it('get_chat_member_count uses correct endpoint (bug fix)', function()
            api.get_chat_member_count(123)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getChatMemberCount'))
            assert.falsy(req.endpoint:find('/getChatMembersCount'))
        end)

        it('set_chat_title truncates to 128 chars', function()
            api.set_chat_title(123, string.rep('a', 200))
            local req = api._last_request()
            assert.equals(128, #req.parameters.title)
        end)

        it('pin_chat_message works', function()
            api.pin_chat_message(123, 42, { disable_notification = true })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/pinChatMessage'))
        end)
    end)

    describe('members', function()
        it('ban_chat_member uses correct endpoint (bug fix)', function()
            api.ban_chat_member(123, 456)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/banChatMember'))
            assert.falsy(req.endpoint:find('/kickChatMember'))
        end)

        it('promote_chat_member includes can_manage_direct_messages', function()
            api.promote_chat_member(123, 456, { can_manage_direct_messages = true })
            local req = api._last_request()
            assert.is_true(req.parameters.can_manage_direct_messages)
        end)
    end)

    describe('inline', function()
        it('answer_callback_query works', function()
            api.answer_callback_query('123', { text = 'Hello!', show_alert = true })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/answerCallbackQuery'))
            assert.equals('Hello!', req.parameters.text)
        end)

        it('answer_inline_query encodes results', function()
            local result = api.inline_result():type('article'):id('1'):title('Test')
                :input_message_content(api.input_text_message_content('Hello'))
            api.answer_inline_query('123', result)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/answerInlineQuery'))
        end)
    end)

    describe('bot', function()
        it('get_file works', function()
            api.get_file('file_id_123')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getFile'))
        end)

        it('set_my_commands works', function()
            api.set_my_commands({
                api.bot_command('start', 'Start'),
                api.bot_command('help', 'Help')
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setMyCommands'))
        end)
    end)

    describe('updates', function()
        it('get_updates works', function()
            api.get_updates({ timeout = 30 })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getUpdates'))
            assert.equals(30, req.parameters.timeout)
        end)

        it('set_webhook works', function()
            api.set_webhook('https://example.com/webhook', { max_connections = 40 })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setWebhook'))
            assert.equals('https://example.com/webhook', req.parameters.url)
        end)
    end)

    describe('payments', function()
        it('send_invoice works', function()
            local prices = api.prices():labeled_price('Item', 100)
            api.send_invoice(123, 'Title', 'Desc', 'payload', 'USD', prices)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendInvoice'))
        end)

        it('refund_star_payment works', function()
            api.refund_star_payment(123, 'charge_id')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/refundStarPayment'))
        end)
    end)
end)
