local poly = require('telegram-bot-lua.polyfill')

describe('polyfill', function()
    describe('bit operations', function()
        it('band works', function()
            assert.equals(0, poly.band(0xFF, 0x00))
            assert.equals(0xFF, poly.band(0xFF, 0xFF))
            assert.equals(0x0F, poly.band(0xFF, 0x0F))
            assert.equals(0x12, poly.band(0xFF, 0x12))
        end)

        it('bor works', function()
            assert.equals(0xFF, poly.bor(0xFF, 0x00))
            assert.equals(0xFF, poly.bor(0xF0, 0x0F))
            assert.equals(0x00, poly.bor(0x00, 0x00))
        end)

        it('bxor works', function()
            assert.equals(0xFF, poly.bxor(0xFF, 0x00))
            assert.equals(0x00, poly.bxor(0xFF, 0xFF))
            assert.equals(0xFF, poly.bxor(0xF0, 0x0F))
        end)

        it('bnot works', function()
            assert.equals(0xFFFFFF00, poly.bnot(0xFF))
            assert.equals(0xFFFFFFFF, poly.bnot(0x00))
        end)

        it('lshift works', function()
            assert.equals(2, poly.lshift(1, 1))
            assert.equals(256, poly.lshift(1, 8))
            assert.equals(0x10000, poly.lshift(1, 16))
            assert.equals(0xFF00, poly.lshift(0xFF, 8))
        end)

        it('rshift works', function()
            assert.equals(1, poly.rshift(2, 1))
            assert.equals(1, poly.rshift(256, 8))
            assert.equals(0xFF, poly.rshift(0xFF00, 8))
            assert.equals(0, poly.rshift(1, 1))
        end)

        it('compound bit operations work', function()
            -- Simulate base64 encoding pattern
            local byte1, byte2, byte3 = 72, 101, 108  -- "Hel"
            local buffer = 0
            buffer = poly.bor(buffer, poly.band(poly.lshift(byte1, 16), 0xff0000))
            buffer = poly.bor(buffer, poly.band(poly.lshift(byte2, 8), 0xff00))
            buffer = poly.bor(buffer, poly.band(byte3, 0xff))

            local b1 = poly.band(poly.rshift(buffer, 18), 0x3f)
            local b2 = poly.band(poly.rshift(buffer, 12), 0x3f)
            local b3 = poly.band(poly.rshift(buffer, 6), 0x3f)
            local b4 = poly.band(buffer, 0x3f)

            assert.is_number(b1)
            assert.is_number(b2)
            assert.is_number(b3)
            assert.is_number(b4)
            assert.truthy(b1 >= 0 and b1 <= 63)
            assert.truthy(b2 >= 0 and b2 <= 63)
            assert.truthy(b3 >= 0 and b3 <= 63)
            assert.truthy(b4 >= 0 and b4 <= 63)
        end)

        it('handles zero correctly', function()
            assert.equals(0, poly.band(0, 0))
            assert.equals(0, poly.bor(0, 0))
            assert.equals(0, poly.lshift(0, 10))
            assert.equals(0, poly.rshift(0, 10))
        end)

        it('handles large values', function()
            assert.equals(0x80000000, poly.lshift(1, 31))
            assert.equals(1, poly.rshift(0x80000000, 31))
        end)
    end)

    describe('table_unpack', function()
        it('unpacks tables', function()
            local a, b, c = poly.table_unpack({10, 20, 30})
            assert.equals(10, a)
            assert.equals(20, b)
            assert.equals(30, c)
        end)

        it('unpacks with range', function()
            local b, c = poly.table_unpack({10, 20, 30}, 2, 3)
            assert.equals(20, b)
            assert.equals(30, c)
        end)

        it('handles empty table', function()
            local result = {poly.table_unpack({})}
            assert.equals(0, #result)
        end)
    end)

    describe('string_pack/string_unpack', function()
        it('has pack and unpack functions', function()
            assert.is_function(poly.string_pack)
            assert.is_function(poly.string_unpack)
        end)

        it('roundtrips integers', function()
            local packed = poly.string_pack('<i4', 42)
            assert.is_string(packed)
            local val = poly.string_unpack('<i4', packed)
            assert.equals(42, val)
        end)

        it('roundtrips multiple values', function()
            local packed = poly.string_pack('<i4i4', 100, 200)
            local a, b = poly.string_unpack('<i4i4', packed)
            assert.equals(100, a)
            assert.equals(200, b)
        end)

        it('handles byte format', function()
            local packed = poly.string_pack('B', 255)
            local val = poly.string_unpack('B', packed)
            assert.equals(255, val)
        end)
    end)

    describe('b64url integration', function()
        it('encode/decode roundtrips with polyfill', function()
            local b64url = require('telegram-bot-lua.b64url')
            local input = 'Hello, World!'
            local encoded = b64url.encode(input)
            assert.is_string(encoded)
            local decoded = b64url.decode(encoded)
            assert.equals(input, decoded)
        end)

        it('handles empty string', function()
            local b64url = require('telegram-bot-lua.b64url')
            assert.equals('', b64url.encode(''))
        end)

        it('handles single byte', function()
            local b64url = require('telegram-bot-lua.b64url')
            local input = 'A'
            assert.equals(input, b64url.decode(b64url.encode(input)))
        end)

        it('handles two bytes', function()
            local b64url = require('telegram-bot-lua.b64url')
            local input = 'AB'
            assert.equals(input, b64url.decode(b64url.encode(input)))
        end)

        it('handles binary data', function()
            local b64url = require('telegram-bot-lua.b64url')
            local input = string.char(0, 1, 2, 127, 128, 255)
            assert.equals(input, b64url.decode(b64url.encode(input)))
        end)

        it('handles long string', function()
            local b64url = require('telegram-bot-lua.b64url')
            local input = string.rep('ABCDEFGHIJ', 100)
            assert.equals(input, b64url.decode(b64url.encode(input)))
        end)
    end)
end)
