-- regression tests for MCP JSON-RPC protocol issues found during the review.
local api = require('spec.test_helper')
local json = require('dkjson')

describe('quality review: mcp', function()
    it('does not crash on a non-table params member', function()
        local response = api.mcp.handle('{"jsonrpc":"2.0","id":1,"method":"tools/call","params":5}')
        assert.is_string(response)
        local decoded = json.decode(response)
        assert.is_table(decoded.error)
        local response2 = api.mcp.handle('{"jsonrpc":"2.0","id":1,"method":"resources/read","params":true}')
        assert.is_string(response2)
        assert.is_table(json.decode(response2).error)
    end)

    it('treats any id-less request as a notification (no response)', function()
        assert.is_nil(api.mcp.handle('{"jsonrpc":"2.0","method":"tools/list"}'))
        assert.is_nil(api.mcp.handle('{"jsonrpc":"2.0","method":"ping"}'))
        assert.is_nil(api.mcp.handle('{"jsonrpc":"2.0","method":"notifications/initialized"}'))
    end)

    it('includes "id":null in parse-error responses', function()
        local response = api.mcp.handle('not json')
        assert.truthy(response:find('"id":null', 1, true))
    end)

    it('encodes empty capabilities as JSON objects, not arrays', function()
        local response = api.mcp.handle('{"jsonrpc":"2.0","id":1,"method":"initialize"}')
        assert.truthy(response:find('"tools":{}', 1, true))
        assert.truthy(response:find('"resources":{}', 1, true))
        assert.is_nil(response:find('"tools":[]', 1, true))
    end)

    it('encodes get_me inputSchema properties as an object', function()
        local response = api.mcp.handle('{"jsonrpc":"2.0","id":1,"method":"tools/list"}')
        assert.is_nil(response:find('"properties":[]', 1, true))
    end)

    it('set_chat_description tool passes the description string, not a table', function()
        api._clear_requests()
        api.mcp.handle('{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"set_chat_description","arguments":{"chat_id":"1","description":"hello"}}}')
        assert.equals('hello', api._last_request().parameters.description)
    end)

    it('ping result encodes as an object', function()
        local response = api.mcp.handle('{"jsonrpc":"2.0","id":7,"method":"ping"}')
        assert.truthy(response:find('"result":{}', 1, true))
    end)
end)
