local api = require('spec.test_helper')
local tools = require('telegram-bot-lua.tools')

describe('tools', function()
    describe('comma_value', function()
        it('formats numbers with commas', function()
            assert.equals('1,000', tools.comma_value(1000))
            assert.equals('1,000,000', tools.comma_value(1000000))
            assert.equals('100', tools.comma_value(100))
        end)

        it('handles negative numbers', function()
            assert.equals('-1,000', tools.comma_value(-1000))
        end)
    end)

    describe('format_ms', function()
        it('formats milliseconds to HH:MM:SS', function()
            assert.equals('00:00:01', tools.format_ms(1000))
            assert.equals('00:01:00', tools.format_ms(60000))
            assert.equals('01:00:00', tools.format_ms(3600000))
        end)

        it('correctly calculates hours (bug fix from v2)', function()
            assert.equals('02:30:00', tools.format_ms(9000000))
            assert.equals('01:01:01', tools.format_ms(3661000))
        end)
    end)

    describe('format_time', function()
        it('returns false for invalid input', function()
            assert.is_false(tools.format_time(nil))
            assert.is_false(tools.format_time('abc'))
        end)

        it('formats seconds', function()
            assert.equals('30 seconds', tools.format_time(30))
            assert.equals('1 second', tools.format_time(1))
        end)

        it('formats minutes', function()
            assert.equals('5 minutes', tools.format_time(300))
            assert.equals('1 minute', tools.format_time(60))
        end)

        it('formats hours', function()
            assert.equals('2 hours', tools.format_time(7200))
            assert.equals('1 hour', tools.format_time(3600))
        end)

        it('formats days', function()
            assert.equals('3 days', tools.format_time(259200))
            assert.equals('1 day', tools.format_time(86400))
        end)

        it('formats weeks', function()
            assert.equals('2 weeks', tools.format_time(1209600))
            assert.equals('1 week', tools.format_time(604800))
        end)
    end)

    describe('round', function()
        it('rounds to nearest integer', function()
            assert.equals(3, tools.round(2.7))
            assert.equals(2, tools.round(2.3))
        end)

        it('rounds to decimal places', function()
            assert.equals(3.14, tools.round(3.14159, 2))
            assert.equals(3.1, tools.round(3.14159, 1))
        end)
    end)

    describe('escape_markdown', function()
        it('escapes markdown special chars', function()
            assert.equals('hello\\_world', tools.escape_markdown('hello_world'))
            assert.equals('\\*bold\\*', tools.escape_markdown('*bold*'))
            assert.equals('\\`code\\`', tools.escape_markdown('`code`'))
        end)
    end)

    describe('escape_markdown_v2', function()
        it('escapes all MarkdownV2 special chars', function()
            local result = tools.escape_markdown_v2('hello_world*bold*[link](url)')
            assert.truthy(string.find(result, '\\_', 1, true))
            assert.truthy(string.find(result, '\\*', 1, true))
            assert.truthy(string.find(result, '\\[', 1, true))
            assert.truthy(string.find(result, '\\]', 1, true))
            assert.truthy(string.find(result, '\\(', 1, true))
            assert.truthy(string.find(result, '\\)', 1, true))
        end)

        it('escapes tildes and pipes', function()
            local result = tools.escape_markdown_v2('~strikethrough~ |table|')
            assert.truthy(string.find(result, '\\~', 1, true))
            assert.truthy(string.find(result, '\\|', 1, true))
        end)
    end)

    describe('escape_html', function()
        it('escapes HTML entities', function()
            assert.equals('&amp;', tools.escape_html('&'))
            assert.equals('&lt;b&gt;', tools.escape_html('<b>'))
        end)
    end)

    describe('escape_bash', function()
        it('wraps in single quotes for safe shell usage', function()
            assert.equals("'hello world'", tools.escape_bash('hello world'))
        end)

        it('handles single quotes in input', function()
            local result = tools.escape_bash("it's")
            assert.equals("'it'\\''s'", result)
        end)

        it('neutralizes dangerous characters', function()
            local result = tools.escape_bash('$(rm -rf /); echo pwned')
            assert.truthy(result:match("^'.*'$"))
        end)
    end)

    describe('utf8_len', function()
        it('counts ASCII characters', function()
            assert.equals(5, tools.utf8_len('hello'))
        end)
    end)

    describe('get_word', function()
        it('returns first word by default', function()
            assert.equals('hello', tools.get_word('hello world'))
        end)

        it('returns nth word', function()
            assert.equals('world', tools.get_word('hello world', 2))
        end)

        it('returns false for nil input', function()
            assert.is_false(tools.get_word(nil))
        end)

        it('returns false for out of range', function()
            assert.is_false(tools.get_word('hello', 5))
        end)
    end)

    describe('input', function()
        it('returns text after first space', function()
            assert.equals('world', tools.input('/command world'))
        end)

        it('returns false for no space', function()
            assert.is_false(tools.input('/command'))
        end)

        it('returns false for nil', function()
            assert.is_false(tools.input(nil))
        end)

        it('preserves multiple arguments', function()
            assert.equals('arg1 arg2 arg3', tools.input('/cmd arg1 arg2 arg3'))
        end)
    end)

    describe('trim', function()
        it('trims whitespace', function()
            assert.equals('hello', tools.trim('  hello  '))
            assert.equals('hello world', tools.trim('  hello world  '))
        end)
    end)

    describe('create_link', function()
        it('creates HTML link', function()
            local link = tools.create_link('Click', 'https://example.com', 'html')
            assert.equals('<a href="https://example.com">Click</a>', link)
        end)

        it('creates markdown link without escaping URL (bug fix)', function()
            local link = tools.create_link('Click', 'https://example.com/path?q=1&r=2', 'markdown')
            assert.truthy(link:find('https://example.com/path'))
            assert.falsy(link:find('\\&'))
        end)

        it('returns plain text when no link', function()
            assert.equals('hello', tools.create_link('hello', nil))
        end)

        it('creates MarkdownV2 link', function()
            local link = tools.create_link('Click', 'https://example.com', 'MarkdownV2')
            assert.truthy(link:find('Click'))
        end)
    end)

    describe('table_size', function()
        it('counts table elements', function()
            assert.equals(3, tools.table_size({a = 1, b = 2, c = 3}))
            assert.equals(0, tools.table_size({}))
        end)
    end)

    describe('table_contains', function()
        it('finds values in table', function()
            assert.is_true(tools.table_contains({1, 2, 3}, 2))
            assert.is_false(tools.table_contains({1, 2, 3}, 4))
        end)

        it('returns false for non-table', function()
            assert.is_false(tools.table_contains('not a table', 1))
        end)
    end)

    describe('is_duplicate', function()
        it('detects duplicates', function()
            assert.is_true(tools.is_duplicate({1, 2, 3, 2}, 2))
            assert.is_false(tools.is_duplicate({1, 2, 3}, 1))
        end)

        it('returns duplicate map when no val given', function()
            local dupes = tools.is_duplicate({1, 2, 3, 2, 3})
            assert.is_true(dupes[2])
            assert.is_true(dupes[3])
            assert.is_nil(dupes[1])
        end)
    end)

    describe('split_string', function()
        it('splits by whitespace', function()
            local parts = tools.split_string('hello world foo')
            assert.equals(3, #parts)
            assert.equals('hello', parts[1])
            assert.equals('foo', parts[3])
        end)

        it('reverses when asked', function()
            local parts = tools.split_string('a b c', true)
            assert.equals('c', parts[1])
            assert.equals('a', parts[3])
        end)
    end)

    describe('string_array_to_table', function()
        it('splits comma separated string', function()
            local parts = tools.string_array_to_table('a,b,c')
            assert.equals(3, #parts)
            assert.equals('a', parts[1])
        end)

        it('trims whitespace from parts', function()
            local parts = tools.string_array_to_table('a, b, c')
            assert.equals('b', parts[2])
        end)
    end)

    describe('random_string', function()
        it('returns empty for zero length', function()
            assert.equals('', tools.random_string(0))
        end)

        it('returns string of correct length', function()
            local s = tools.random_string(10)
            assert.equals(10, #s)
        end)

        it('returns table of strings for amount', function()
            local t = tools.random_string(5, 3)
            assert.is_table(t)
            assert.equals(3, #t)
            assert.equals(5, #t[1])
        end)

        it('only contains alphanumeric chars', function()
            local s = tools.random_string(100)
            assert.truthy(s:match('^[%w]+$'))
        end)
    end)

    describe('is_valid_url', function()
        it('validates URLs', function()
            assert.is_true(tools.is_valid_url('https://example.com'))
            assert.is_true(tools.is_valid_url('http://test.org/path'))
        end)

        it('auto-prepends http://', function()
            assert.is_true(tools.is_valid_url('example.com'))
        end)

        it('returns parts when asked', function()
            local parts = tools.is_valid_url('https://example.com/path', true)
            assert.is_table(parts)
            assert.truthy(parts.tld)
        end)

        it('returns false for nil', function()
            assert.is_false(tools.is_valid_url(nil))
        end)
    end)

    describe('service_message', function()
        it('detects new_chat_member', function()
            local is, kind = tools.service_message({ new_chat_member = {} })
            assert.is_true(is)
            assert.equals('new_chat_member', kind)
        end)

        it('detects forum events', function()
            local is, kind = tools.service_message({ forum_topic_created = {} })
            assert.is_true(is)
            assert.equals('forum_topic_created', kind)
        end)

        it('detects giveaway events', function()
            assert.is_true(tools.service_message({ giveaway_created = {} }))
            assert.is_true(tools.service_message({ giveaway = {} }))
        end)

        it('returns false for regular messages', function()
            assert.is_false(tools.service_message({ text = 'hello' }))
        end)
    end)

    describe('is_media', function()
        it('detects photos', function()
            assert.is_true(tools.is_media({ photo = {{}} }))
        end)

        it('detects animations', function()
            assert.is_true(tools.is_media({ animation = {} }))
        end)

        it('detects paid_media', function()
            assert.is_true(tools.is_media({ paid_media = {} }))
        end)

        it('returns false for text', function()
            assert.is_false(tools.is_media({ text = 'hello' }))
        end)
    end)

    describe('media_type', function()
        it('returns correct type for each media', function()
            assert.equals('audio', tools.media_type({ audio = {} }))
            assert.equals('photo', tools.media_type({ photo = {{}} }))
            assert.equals('video', tools.media_type({ video = {} }))
            assert.equals('animation', tools.media_type({ animation = {} }))
            assert.equals('sticker', tools.media_type({ sticker = {} }))
            assert.equals('paid_media', tools.media_type({ paid_media = {} }))
        end)

        it('detects text', function()
            assert.equals('text', tools.media_type({ text = 'hello' }))
        end)

        it('returns empty for unknown', function()
            assert.equals('', tools.media_type({}))
        end)
    end)

    describe('file_id', function()
        it('extracts audio file_id', function()
            assert.equals('abc', tools.file_id({ audio = { file_id = 'abc', file_unique_id = 'xyz' }}))
        end)

        it('extracts unique file_id', function()
            assert.equals('xyz', tools.file_id({ audio = { file_id = 'abc', file_unique_id = 'xyz' }}, true))
        end)

        it('gets highest res photo', function()
            local msg = { photo = {
                { file_id = 'small', file_unique_id = 'u1' },
                { file_id = 'large', file_unique_id = 'u2' }
            }}
            assert.equals('large', tools.file_id(msg))
        end)

        it('returns empty for non-media', function()
            assert.equals('', tools.file_id({ text = 'hello' }))
        end)
    end)

    describe('file operations', function()
        it('file_exists works', function()
            assert.is_true(tools.file_exists('src/config.lua'))
            assert.is_false(tools.file_exists('/nonexistent/file'))
        end)

        it('read_file works', function()
            local content = tools.read_file('src/config.lua')
            assert.is_string(content)
            assert.truthy(content:find('endpoint'))
        end)

        it('read_file returns false for nil', function()
            assert.is_false(tools.read_file(nil))
        end)

        it('get_file_as_table works', function()
            local lines = tools.get_file_as_table('src/config.lua')
            assert.is_table(lines)
            assert.truthy(#lines > 0)
        end)

        it('json_to_table works', function()
            tools.save_to_file('{"key":"value"}', 'test_json.json')
            local t = tools.json_to_table('/tmp/test_json.json')
            assert.equals('value', t.key)
            os.remove('/tmp/test_json.json')
        end)

        it('save_to_file sanitizes filename', function()
            local path = tools.save_to_file('test', '../../etc/passwd')
            assert.truthy(path:match('^/tmp/'))
            assert.falsy(path:find('%.%.'))
            if path then os.remove(path) end
        end)
    end)

    describe('get_formatted_user', function()
        it('returns false for missing params', function()
            assert.is_false(tools.get_formatted_user(nil, 'Name'))
            assert.is_false(tools.get_formatted_user(123, nil))
        end)

        it('formats HTML user link', function()
            local result = tools.get_formatted_user(123, 'Test User', 'HTML')
            assert.truthy(result:find('tg://user'))
            assert.truthy(result:find('Test User'))
        end)

        it('formats MarkdownV2 by default (bug fix)', function()
            local result = tools.get_formatted_user(123, 'Test_User')
            assert.truthy(result:find('tg://user'))
        end)

        it('handles boolean parse_mode (bug fix from v2)', function()
            local result = tools.get_formatted_user(123, 'Test', true)
            assert.is_string(result)
            assert.truthy(result:find('tg://user'))
        end)
    end)

    describe('commands', function()
        it('creates command matcher', function()
            local cmds = tools.commands('test_bot')
            cmds:command('start')
            assert.equals(4, #cmds.table)
        end)

        it('matches command patterns', function()
            local cmds = tools.commands('test_bot')
            cmds:command('help')
            local text = '/help'
            local matched = false
            for _, pattern in pairs(cmds.table) do
                if text:match(pattern) then matched = true; break end
            end
            assert.is_true(matched)
        end)

        it('matches command with bot username', function()
            local cmds = tools.commands('test_bot')
            cmds:command('help')
            local text = '/help@test_bot'
            local matched = false
            for _, pattern in pairs(cmds.table) do
                if text:match(pattern) then matched = true; break end
            end
            assert.is_true(matched)
        end)
    end)

    describe('pretty_print', function()
        it('returns formatted JSON', function()
            local result = tools.pretty_print({ key = 'value' })
            assert.is_string(result)
            assert.truthy(result:find('key'))
        end)
    end)

    describe('file_size', function()
        it('returns false for invalid input', function()
            local result, err = tools.file_size(42)
            assert.is_false(result)
        end)

        it('returns false for nonexistent file', function()
            local result, err = tools.file_size('/nonexistent/file')
            assert.is_false(result)
            assert.equals('Could not open file!', err)
        end)

        it('returns size for existing file', function()
            tools.save_to_file('test content', 'size_test.txt')
            local size = tools.file_size('/tmp/size_test.txt')
            assert.is_number(size)
            assert.truthy(size > 0)
            os.remove('/tmp/size_test.txt')
        end)
    end)

    describe('rle_encode/decode', function()
        it('roundtrips correctly', function()
            local input = 'hello'
            assert.equals(input, tools.rle_decode(tools.rle_encode(input)))
        end)
    end)
end)
